with-expecter: true
disable-version-string: true
packages:
  github.com/CrowhopTech/ttstream/orchestrator:
    interfaces:
      redisClient:
        config:
          filename: "mock_redis_client_test.go"
          dir: "."
          mockname: "MockRedisClient"
          outpkg: "main"
